/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118301-g851a84650e-20250113"
#endif /* AVUTIL_FFVERSION_H */
